service: favi

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 180
  profile: tremorlab
  environment:
    DEBUG: "*"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:*:*

package:
  exclude:
    - seed.rb
    - '*.csv*'
    - ruby
    - vendor
    - .bundle 
    - '*.rb'
    - 'Gemfile*'

functions:
  createFave:
    handler: handlers/handler.createFave
    environment:
    events:
      - http:
          path: /faves
          method: post
  streamFunction:
    handler: handlers/stream.faveStreamEvent
    events:
       - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - FavesDynamoDbTable
              - StreamArn
          batchSize: 1

resources:
  Resources:
    FavesDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FaveRecords
        AttributeDefinitions:
          - AttributeName: hostname
            AttributeType: "S"
        KeySchema:
          - AttributeName: hostname
            KeyType: HASH
        StreamSpecification:
            StreamViewType: NEW_AND_OLD_IMAGES
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25